#!/bin/zsh
# Set up symlinks to set a ghc version as the default.

version=$1
prefix=$2

if [[ -z $version || -z $prefix ]]; then
    echo "usage: $0 7.10.1 /usr/local/bin"
    exit 1
fi

unversioned=(hsc2hs)

bin=(runghc ghc ghci ghc-pkg hsc2hs haddock)

for f in $unversioned; do
    if [[ ! -h $prefix/$f ]]; then
        echo $prefix/$f is unversioned
        exit 1
    fi
done

for f in $bin; do
    echo ln -sf $prefix/$f-$version $f
done

echo -n 'ok? '
read ok
if [[ $ok != y ]]; then
    exit 1
fi

for f in $bin; do
    ln -sf $prefix/$f-$version $f
done
