#!/bin/zsh
# Remove a ghc install of the given version.

ver=$1
bin=/usr/local/bin
lib=/usr/local/lib

binaries=(runghc ghc ghci ghc-pkg hsc2hs haddock-ghc)

dir=$(ghc-$ver --print-libdir)

rm_bins=($dir $bin/${^binaries}-$ver)
rm_libs=($lib/ghc-$ver ~/.cabal/{lib,share,share/doc}/*-ghc-$ver(N))

du -hsc $rm_bins $rm_libs
echo -n 'remove? '
read response
if [[ $response = y ]]; then
    sudo rm -rf $rm_bins $rm_libs
fi
