#!/bin/zsh
# Remove a package, but only if no other installed packages depend on it.

package=$1

# Don't mess with global packages.
if [[ $UID -eq 0 ]]; then
    echo "don't be root"
    exit 1
fi

if ! ghc-pkg describe $package >/dev/null; then
    echo no such package: $package
    exit 1
fi

ghcdir=$(ghc --print-libdir)

function field() {
    ghc-pkg field $package $1 | cut -d' ' -f2-
    return $?
}

libdir=$(field library-dirs)
hidir=$(field import-dirs)
html=$(dirname $(field haddock-html))

echo rm -rf $libdir $hidir $html
echo -n 'remove? '
read response
if [[ $response = y ]]; then
    # ghc-pkg unregister will complain if this will break other packages
    if ! ghc-pkg unregister $package; then
        exit 1
    fi
    rm -rf $libdir $hidir $html
fi

